#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Zsh
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

# Composer
ln -sf $DOTFILES/composer/composer.json $HOME/.composer/composer.json

# Starship
ln -sf $DOTFILES/starship/starship.toml $HOME/.config/starship.toml

# Kitty
rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

# Tmux
# mkdir -p $HOME/.config/tmux
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# Neovim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# Scripts
mkdir -p $HOME/.local/bin
ln -sf $DOTFILES/scripts/t $HOME/.local/bin/t
ln -sf $DOTFILES/scripts/wpcode $HOME/.local/bin/wpcode
ln -sf $DOTFILES/scripts/wpcreate $HOME/.local/bin/wpcreate
ln -sf $DOTFILES/scripts/wpdestroy $HOME/.local/bin/wpdestroy
ln -sf $DOTFILES/scripts/phpcreate $HOME/.local/bin/phpcreate
ln -sf $DOTFILES/scripts/phpdestroy $HOME/.local/bin/phpdestroy
ln -sf $DOTFILES/scripts/setsecret $HOME/.local/bin/setsecret
ln -sf $DOTFILES/scripts/getsecret $HOME/.local/bin/getsecret

# .env symlink
ln -sf $DOTFILES/.env $HOME/.dotfiles-env

