#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Zsh
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

# Git
ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig

# Starship
ln -sf $DOTFILES/starship/starship.toml $HOME/.config/starship.toml

# Kitty
rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

# Tmux
# mkdir -p $HOME/.config/tmux
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# Neovim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# Scripts
mkdir -p $HOME/.local/bin
ln -sf $DOTFILES/scripts/t $HOME/.local/bin/t

# .env symlink
ln -sf $DOTFILES/.env $HOME/.dotfiles-env

