#!/bin/sh
# vim: filetype=sh

ACCOUNT="$1"
SERVICE="$2"

if [ -z "$ACCOUNT" ] || [ -z "$SERVICE" ]; then
  echo "Usage: getsecret <account> <service>"
  exit 1
fi

security find-generic-password -a "$ACCOUNT" -s "$SERVICE" -w 2>/dev/null
