#!/bin/sh
# vim: filetype=sh

ACCOUNT="$1"
SERVICE="$2"
SECRET="$3"

if [ -z "$ACCOUNT" ] || [ -z "$SERVICE" ] || [ -z "$SECRET" ]; then
  echo "Usage: setsecret <account> <service> <secret>"
  exit 1
fi

security add-generic-password -a "$ACCOUNT" -s "$SERVICE" -w "$SECRET" -U
